"""Snippet table public key added

Revision ID: 30f84b793702
Revises: de8a104e89c6
Create Date: 2026-09-04 22:16:56.934497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f84b793702'
down_revision: Union[str, Sequence[str], None] = 'de8a104e89c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('public_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_snippets_public_id'), 'snippets', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_public_id'), table_name='snippets')
    op.drop_column('snippets', 'public_id')
    # ### end Alembic commands ###
