"""Snippet Table

Revision ID: de8a104e89c6
Revises: 8c0bfa168e54
Create Date: 2026-09-04 18:48:49.993430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8a104e89c6'
down_revision: Union[str, Sequence[str], None] = '8c0bfa168e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'UNLISTED', 'PRIVATE', name='visiblevalue'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippets_owner_id'), 'snippets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_snippets_title'), 'snippets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_title'), table_name='snippets')
    op.drop_index(op.f('ix_snippets_owner_id'), table_name='snippets')
    op.drop_table('snippets')
    # ### end Alembic commands ###
